config/routes.rb
Rails.application.routes.draw do
  root 'storefront#all_items'

  resources :categories
  resources :items
    resources :conversations do
      member do
        post :reply
        post :trash
        post :untrash
    end
  end

  devise_for :users

  get 'my_items' => 'items#my_items'
  get 'categorical' => 'storefront#items_by_category'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  belongs_to :category
  validates :title, presence: true
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  before_filter :authenticate_user!, except: [:index]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new

    @categories = Category.all

  end

  # GET /items/1/edit
  def edit

    @categories = Category.all

  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params

      params.require(:item).permit(:title, :description, :price, :user_id, :image, :category_id)

      params.require(:item).permit(:title, :description, :price, :user_id)

    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">

    <%= f.label "Photo: " %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select(:category_id, @categories.collect {|c| [c.name, c.id ] }, {:include_blank => 'Please select a category'}) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |

<%= link_to 'Back', my_items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "row">
    <% @items.each do |item| %>
        <div class = "col-md-4">
            <div class = "panel panel-default">
                <div class = "panel-body">
                      <p><strong><%= item.title %></strong></p>
                       <div style = "height:150px;">
                           <%= image_tag item.image.url(:thumb) %>
                       </div>
                    <p><a href="#">
                        <span class = "glyphicon glyphicon-plus"></span>quick info
                    </a></p>
                    <p><strong><%= number_to_currency item.price %></strong></p>
                    <div style="height:150px;">
                        <p><%= item.description %></p>
                    </div>
                    <p>Posted by: <%= item.user.username %></p>
                </div>
            </div>
        </div>
    <%end%>
</div>

app/views/items/my_items.html.erb
<h2><%= current_user.username.capitalize %>'s Items</h2>
<% current_user.items.each do |item| %>
<div class="col-md-12">
    <div class= 'panel'>
      <div class= 'panel-heading'>
          <h4><strong><%=link_to item.title, item%></strong></h4>
      </div>
      <div class= 'panel-body'>
         <div style = "height:150px;">
                           <%= image_tag item.image.url(:thumb) %>
                       </div>
          <p><%= item.description[0..100] %>...</p>
          <p>[<%=link_to 'READ MORE', item%>]</p>
          <p><strong><%= number_to_currency item.price %></strong></p>
          <p>Created at: <%= item.created_at.strftime('%D at %r')%></p>
          <p>Last updated: <%= item.updated_at.strftime('%D at %r')%></p>
      </div>
        <%=link_to 'Edit', edit_item_path(item), class: 'btn btn-warning' %>
        <%=link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?'}, class:'btn btn-danger' %>
    </div>
  </div>
<%end%>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>


<%= link_to 'Back', my_items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>User:</strong>

  <%= @item.user.username %>

</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>