config/routes.rb
Rails.application.routes.draw do
  root 'storefront#all_items'

  resources :categories
  resources :items
    resources :conversations do
      member do
        post :reply
        post :trash
        post :untrash
    end
  end

  devise_for :users

  get 'my_items' => 'items#my_items'
  get 'categorical' => 'storefront#items_by_category'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fliptrade</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", 'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js' %>
  
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        
      <%= link_to "FlipTrade", root_path, class: "navbar-brand" %>
      
      <ul class="nav navbar-nav">
        <li><%= link_to "All Items", root_path %></li>
        <li><%= link_to "My Items", my_items_path %></li>
        <li><%= link_to "Add Item", new_item_path %></li>
        
        <li class = "dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Category<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |cat| %>
          <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
          <%end%>
        </ul>
        </li>
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inbox", mailbox_inbox_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <li> <%= link_to "Edit Profile", edit_user_registration_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%else%>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <ul class="nav navbar-nav">
        <a class="navbar-brand" href="#">Brand</a>
        <li><%= link_to "All Items", items_path %></li>
        <li class = "dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find By Category<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |cat| %>
          <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
          <%end%>
        </ul>
        </li>
      </ul>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%end%>

<%= yield %>

</body>
</html>